name: fis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9.7
  - cudatoolkit=10.2
  - pytorch=1.10.1
  - torchvision=0.11.2
  - torchaudio=0.10.1
  - numpy=1.21.2
  - pip
  - pip:
      - iopath==0.1.10
      - jmespath==1.0.1
      - marshmallow==3.22.0
      - mypy-extensions==1.0.0
      - portalocker==2.10.1
      - python-dateutil==2.9.0.post0
      - regex==2024.9.11
      - typing-inspect==0.9.0
