#CUDA_VISIBLE_DEVICES=4 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0219clip_agg_embed_pretraining_sim_only_ortho_loss --ortho_loss --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-3 --epoch 150 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 16 &
#CUDA_VISIBLE_DEVICES=4 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0219clip_agg_embed_pretraining_sim_only_peak_loss --peak_loss --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-3 --epoch 150 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 16 &
#CUDA_VISIBLE_DEVICES=4 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0219clip_agg_embed_pretraining_sim_only_ortho_peak_loss --ortho_loss --peak_loss --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-3 --epoch 150 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 16


CUDA_VISIBLE_DEVICES=3 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0219_clip_rubric_with_goeSimOrthoPeakPre --ortho_loss --peak_loss --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 8  --ckpt 0219clip_agg_embed_pretraining_sim_only_ortho_peak_loss_pretraining_best &
CUDA_VISIBLE_DEVICES=3 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0219_clip_rubric_with_goeSimOrthoPre --ortho_loss --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 8  --ckpt 0219clip_agg_embed_pretraining_sim_only_ortho_loss_pretraining_best &
CUDA_VISIBLE_DEVICES=3 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0219_clip_rubric_with_goeSimPeakPre --peak_loss --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 8  --ckpt 0219clip_agg_embed_pretraining_sim_only_peak_loss_pretraining_best &
CUDA_VISIBLE_DEVICES=3 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0219_clip_rubric_peak_loss_only --peak_loss --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 8  &

CUDA_VISIBLE_DEVICES=3 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0219_clip_rubric_with_goeSimPeakPre --peak_loss --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 8  --ckpt 0219_clip_rubric_with_goeSimPeakPre_best --test