#CUDA_VISIBLE_DEVICES=4 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0219clip_agg_embed_pretraining_sim_only_ortho_peak_posThresh_2_negThresh_-1 --pretraining_threshold_pos 2 --pretraining_threshold_neg -1 --ortho_loss --peak_loss --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-5 --epoch 150 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 16 &
#CUDA_VISIBLE_DEVICES=4 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0219clip_agg_embed_pretraining_sim_only_ortho_peak_posThresh_2_negThresh_-1.5 --pretraining_threshold_pos 2 --pretraining_threshold_neg -1.5 --ortho_loss --peak_loss  --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-5 --epoch 150 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 16 &
#CUDA_VISIBLE_DEVICES=4 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0219clip_agg_embed_pretraining_sim_only_ortho_peak_posThresh_1_negThresh_-1 --pretraining_threshold_pos 1 --pretraining_threshold_neg -1.0 --ortho_loss --peak_loss  --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-5 --epoch 150 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 16 &


CUDA_VISIBLE_DEVICES=2 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0220clip_agg_embed_pretraining_sim_dissim_1e-1_margin_0  --enforce_dissimilarity --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr  1e-1 --epoch 300 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 16 &
CUDA_VISIBLE_DEVICES=2 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0220clip_agg_embed_pretraining_sim_dissim_random_sample_1e-1_margin_0  --enforce_dissimilarity --randomly_sample_dissim --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr  1e-1 --epoch 300 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 16 &

#CUDA_VISIBLE_DEVICES=3 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0220clip_agg_embed_pretraining_sim_dissim_debug  --enforce_dissimilarity --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-5 --epoch 300 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 16

