CUDA_VISIBLE_DEVICES=5 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0327clip_simplified_regularization_finetuning --ortho_loss --peak_loss --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 4  --ckpt 0321clip_simplified_regularization_pretraining_best  --rubric_simplified &
CUDA_VISIBLE_DEVICES=5 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0327clip_simplified_regularization_sig_finetuning --ortho_loss --peak_loss --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 4  --rescaling --ckpt 0321clip_simplified_regularization_pretraining_best  --rubric_simplified &

CUDA_VISIBLE_DEVICES=5 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0327clip_simplified_regularization_with_dissimilarity_finetuning --ortho_loss --peak_loss --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 4  --ckpt 0322clip_simplified_regularization_with_dissimilarity_pretraining_best --rubric_simplified &
CUDA_VISIBLE_DEVICES=5 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0327clip_simplified_regularization_with_dissimilarity_sig_finetuning --ortho_loss --peak_loss --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 4  --rescaling --ckpt 0322clip_simplified_regularization_with_dissimilarity_pretraining_best  --rubric_simplified &

sleep 30m

CUDA_VISIBLE_DEVICES=5 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0327clip_simplified_hand_negatives_regularization_with_dissimilarity_finetuning --ortho_loss --peak_loss --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 4  --ckpt 0322clip_simplified_hand_negatives_regularization_with_dissimilarity_pretraining_best  --rubric_simplified &
CUDA_VISIBLE_DEVICES=5 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0327clip_simplified_hand_negatives_regularization_with_dissimilarity_sig_finetuning --ortho_loss --peak_loss --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 4  --rescaling --ckpt 0322clip_simplified_hand_negatives_regularization_with_dissimilarity_pretraining_best --rubric_simplified &

