# simplified only visual-text similarity
CUDA_VISIBLE_DEVICES=3 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0327clip_simplified_regularization_w_bug_fix --pretraining_threshold_pos 2 --pretraining_threshold_neg -2 --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-2 --epoch 300 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 32 --rubric_simplified --peak_loss --ortho_loss &

# simplified and text prompt
CUDA_VISIBLE_DEVICES=3 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0327clip_simplified_use_text_prompt_regularization_w_bug_fix --pretraining_threshold_pos 2 --pretraining_threshold_neg -2 --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-2 --epoch 300 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 32 --rubric_simplified --rubric_use_text_prompt --peak_loss --ortho_loss &
# simplified only visual-text similarity + hand negatives dissimilarity
## lr 1e-2
CUDA_VISIBLE_DEVICES=3 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0327clip_simplified_hand_negatives_regularization_with_dissimilarity_w_bug_fix --pretraining_threshold_pos 2 --pretraining_threshold_neg -2 --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-2 --epoch 300 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 32 --rubric_simplified --rubric_hand_negatives --enforce_dissimilarity --peak_loss --ortho_loss &
CUDA_VISIBLE_DEVICES=3 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0327clip_simplified_regularization_with_dissimilarity_w_bug_fix --pretraining_threshold_pos 2 --pretraining_threshold_neg -2 --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-2 --epoch 300 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 32 --rubric_simplified --enforce_dissimilarity --peak_loss --ortho_loss &
## lr 1e-5
