CUDA_VISIBLE_DEVICES=5 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES \
--model-name 0423_joint_pretraining_vis_triplet_margin_0.05 --pretraining_threshold_pos 1.3 --pretraining_threshold_neg -2 --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-2 --epoch 300 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 32  --use_visual_text_triplet_loss --rubric_hand_negatives --rubric_simplified --peak_loss --ortho_loss --dist_metric cosine --margin 0.5 --reg_weight 0.1 \
--visual_triplet_loss --visual_triplet_margin 0.05  --joint_pretraining &

CUDA_VISIBLE_DEVICES=5 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES \
--model-name 0423_joint_pretraining_vis_triplet_margin_0.5 --pretraining_threshold_pos 1.3 --pretraining_threshold_neg -2 --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-2 --epoch 300 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 32  --use_visual_text_triplet_loss --rubric_hand_negatives --rubric_simplified --peak_loss --ortho_loss --dist_metric cosine --margin 0.5 --reg_weight 0.1 \
--visual_triplet_loss --visual_triplet_margin 0.5  --joint_pretraining &

CUDA_VISIBLE_DEVICES=5 python main.py --video-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /afs/cs.pitt.edu/usr0/arr159/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES \
--model-name 0423_joint_pretraining_vis_triplet_rel_margin --pretraining_threshold_pos 1.3 --pretraining_threshold_neg -2 --pretraining --pretraining_agg embed  --clip_embedding_path text_embeddings_and_weights.pth --clip-num 128 --lr 1e-2 --epoch 300 --n_encoder 1 --n_decoder 2 --n_query 7 --batch 32  --use_visual_text_triplet_loss --rubric_hand_negatives --rubric_simplified --peak_loss --ortho_loss --dist_metric cosine --margin 0.5 --reg_weight 0.1 \
--visual_triplet_loss --visual_triplet_margin -1  --joint_pretraining &