# no pretraining, no ISR
# python main.py --video-path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name no_action_mask_plain --optim rmsprop --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 4 --rescaling --rubric_simplified --vid_id_to_element_list_path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/elements_preprocessing/vid_id_to_element_list.json & 

python main.py --video-path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0902_plain_no_pretrainig --action_rubric_mask --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 4   --rescaling --rubric_simplified --vid_id_to_element_list_path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/elements_preprocessing/vid_id_to_element_list.json & 

python main.py --video-path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0902_plain_no_pretraining2 --action_rubric_mask --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 4   --rescaling --rubric_simplified --vid_id_to_element_list_path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/elements_preprocessing/vid_id_to_element_list.json  


# ISR

python main.py --video-path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/fis-v/swintx_avg_fps25_clip32 --train-label-path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/fis-v/train.txt --test-label-path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/fis-v/test.txt --score-type TES --model-name 0902_plain_isr_no_pretrainig --ortho_loss --peak_loss --action_rubric_mask --optim rmsprop  --clip-num 128 --lr 1e-5 --epoch 320 --n_encoder 1 --n_decoder 2 --n_query 7 --alpha 1.0 --margin 1.0 --lr-decay cos --decay-rate 0.01 --dropout 0.3 --clip_embedding_path text_embeddings_and_weights.pth --n-workers 4 --rescaling --rubric_simplified --vid_id_to_element_list_path /ihome/akovashka/arr159/figure_skating_code/figure_skating/CVPR22_GDLT/elements_preprocessing/vid_id_to_element_list.json & 
